# docker-compose -f LNX-docker-compose.yml --env-file LNX.env up --build --exit-code-from matlab
version: '2.2'
services:
  app:
    environment:
    - DISPLAY
    image: raphaelguzman/pipuploader:v0.1
    build:
      context: .
    working_dir: /src
    volumes:
      - .:/src
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: > 
      sh -c "
        # for signing with gpg
        # apk add gnupg;
        # gpg --import datajoint-dev.private.key;
        tail -f /dev/null;
        ./pypi_package.sh /src/core;
        # pip install --upgrade --user -i https://test.pypi.org/simple maz;
        # pip uninstall -y maz;
        ./pypi_package.sh /src/addon-unofficial;
        # pip install --upgrade --user -i https://test.pypi.org/simple mzaddon_user_raphael;
        # pip uninstall -y mzaddon_user_raphael;
        ./pypi_package.sh /src/addon-official;
        # pip install --upgrade --user -i https://test.pypi.org/simple mzaddon_type_student;
        # pip uninstall -y mzaddon_type_student;
      "
      